version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: snippet-vault-db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: snippet-vault-backend
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mini-snippet-vault
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: snippet-vault-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next

volumes:
  mongodb_data:
